In [5]:
import pandas as pd

df = pd.read_excel('../data/Telco_customer_churn.xlsx')

df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

In [8]:
df.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='object')

In [9]:
df['Churn Label'].value_counts(normalize=True)

Churn Label
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64

In [10]:
df['Churn Value'].mean()

0.2653698707936959

In [11]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.columns

Index(['customerid', 'count', 'country', 'state', 'city', 'zip_code',
       'lat_long', 'latitude', 'longitude', 'gender', 'senior_citizen',
       'partner', 'dependents', 'tenure_months', 'phone_service',
       'multiple_lines', 'internet_service', 'online_security',
       'online_backup', 'device_protection', 'tech_support', 'streaming_tv',
       'streaming_movies', 'contract', 'paperless_billing', 'payment_method',
       'monthly_charges', 'total_charges', 'churn_label', 'churn_value',
       'churn_score', 'cltv', 'churn_reason'],
      dtype='object')

In [13]:
pd.crosstab(df['contract'], df['churn_value'], normalize='index')

churn_value            0         1
contract
Month-to-month  0.572903  0.427097
One year        0.887305  0.112695
Two year        0.971681  0.028319

In [14]:
pd.crosstab(df['internet_service'], df['churn_value'], normalize='index')

churn_value              0         1
internet_service
DSL               0.810409  0.189591
Fiber optic       0.581072  0.418928
No                0.925950  0.074050

In [15]:
pd.crosstab(df['payment_method'], df['churn_value'], normalize='index')

churn_value                       0         1
payment_method
Bank transfer (automatic)  0.832902  0.167098
Credit card (automatic)    0.847569  0.152431
Electronic check           0.547146  0.452854
Mailed check               0.808933  0.191067

In [16]:
pd.crosstab(pd.cut(df['tenure_months'], bins=[0,12,24,48,72]),
            df['churn_value'],
            normalize='index')

churn_value           0         1
tenure_months
(0, 12]        0.523218  0.476782
(12, 24]       0.712891  0.287109
(24, 48]       0.796110  0.203890
(48, 72]       0.904868  0.095132

In [17]:
pd.crosstab(df['contract'], df['churn_value'], normalize='index')

churn_value            0         1
contract
Month-to-month  0.572903  0.427097
One year        0.887305  0.112695
Two year        0.971681  0.028319

In [18]:
pd.crosstab(
    pd.cut(df['tenure_months'], bins=[0,12,24,48,72]),
    df['churn_value'],
    normalize='index'
)

churn_value           0         1
tenure_months
(0, 12]        0.523218  0.476782
(12, 24]       0.712891  0.287109
(24, 48]       0.796110  0.203890
(48, 72]       0.904868  0.095132

In [19]:
pd.crosstab(
    [df['contract'], pd.cut(df['tenure_months'], bins=[0,12,24,48,72])],
    df['churn_value'],
    normalize='index'
)

churn_value                          0         1
contract       tenure_months
Month-to-month (0, 12]        0.486459  0.513541
               (12, 24]       0.622795  0.377205
               (24, 48]       0.670823  0.329177
               (48, 72]       0.739766  0.260234
One year       (0, 12]        0.894309  0.105691
               (12, 24]       0.918782  0.081218
               (24, 48]       0.893822  0.106178
               (48, 72]       0.870662  0.129338
Two year       (0, 12]        1.000000  0.000000
               (12, 24]       1.000000  0.000000
               (24, 48]       0.978102  0.021898
               (48, 72]       0.966746  0.033254

In [20]:
high_risk = df[
    (df['contract'] == 'Month-to-month') &
    (df['tenure_months'] <= 12) &
    (df['monthly_charges'] > df['monthly_charges'].median())
]

high_risk['churn_value'].mean()

0.6995073891625616